[package]
name = "scripter"
version = "0.1.0"
authors = ["Jakub Stasiak <jakub@stasiak.at>"]
edition = "2018"
description = "A good looking LaTeX script/screenplay compiler"
license = "MIT"

[dependencies]
