The Alienant, version 1
Firstname Lastname

INT. SPACE STATION

Dark corridor. Something lurks in the shadows.

EXT. MILITARY BASE -- DAY

COLONEL SMITH smokes a cigarette. There are items on his desk: a bottle of whisky, a gun and a doll. SMITH looks up as CAPTAIN PARKER approaches.

CAPTAIN PARKER doesn't look too well.

	SMITH: So, it's begun.
	PARKER: Yes. (inhales) Yes, it has.
	SMITH: I was afraid it'd come to this. Look: how about we –
	PARKER: No.
